## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.0
  - 1.3
  - nightly
env:
  - CONDA_JL_VERSION="2"
  - CONDA_JL_VERSION="3"
  - CONDA_JL_VERSION="3" IPYTHON_JL_IPYTHON_DEP_NAME="ipython-pre"
  - CONDA_JL_VERSION="3" IPYTHON_JL_IPYTHON_DEP_NAME="ipython-dev"
notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: nightly

coveralls: true
codecov: true
